version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:${IMAGE_VERSION:-7.10.1}
    container_name: standalone.pub-elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - discovery.type=single-node 
      - bootstrap.memory_lock=true 
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
      - log:/usr/share/elasticsearch/logs
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "200m"
    networks:
      - custom-network
networks:
  custom-network:
    driver: bridge
volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: /opt/pub-elasticsearch/data/data
      o: bind
  log:
    driver: local
    driver_opts:
      type: none
      device: /opt/pub-elasticsearch/data/log
      o: bind