services:
  nginx:
    image: nginx:1.27-alpine
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 200m
    restart: always
    volumes:
      - conf.d:/etc/nginx/conf.d
      - www:/usr/share/nginx
      - ${PWD}/data/etc/nginx.conf:/etc/nginx/nginx.conf
    container_name: standalone.pub-nginx
    hostname: standalone.pub-nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - custom-network
networks:
  custom-network:
    driver: bridge
volumes:
  conf.d:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/conf.d
      o: bind
  www:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/www
      o: bind
