services:
  mysql:
    image: mysql:${IMAGE_VERSION:-8.0}
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 200m
    restart: always
    volumes:
      - pub_mysql_data:/var/lib/mysql
      - pub_mysql_log:/var/log/mysql
      - pub_mysql_conf:/etc/mysql/conf.d
      - /opt:/var/run/mysqld
    container_name: standalone.pub-mysql
    hostname: standalone.pub-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD:-false}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-admin}
      # These 3 vairables are optional,  allows you to specify the name of a database to be created on image startup. 
      # If a user/password was supplied (see below) then that user will be granted superuser access to this database.
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-changeMe123}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-test}
    ports:
      - 3306:3306 # change the port if local 3306 is in use
      - 33060:33060 # change the port if local 33060 is in use
    networks:
      - custom-network
networks:
  custom-network:
    driver: bridge
volumes:
  pub_mysql_data:
  pub_mysql_log:
  pub_mysql_conf: