version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:${IMAGE_VERSION:-3.8.14}
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 200m
    restart: always
    volumes:
      - data:/var/lib/rabbitmq
      - log:/var/log/rabbitmq
      - conf:/etc/rabbitmq
    container_name: standalone.pub-rabbitmq
    hostname: standalone.pub-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 25672:25672
      - 15671:15671
      - 15672:15672
      - 61613:61613
      - 61614:61614
      - 15674:15674
      - 15692:15692
    networks:
      - custom-network
networks:
  custom-network:
    driver: bridge
volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: /opt/pub-rabbitmq/data/data
      o: bind
  log:
    driver: local
    driver_opts:
      type: none
      device: /opt/pub-rabbitmq/data/log
      o: bind
  conf:
    driver: local
    driver_opts:
      type: none
      device: /opt/pub-rabbitmq/data/conf
      o: bind
