services:
  mongodb:
    image: mongo:${IMAGE_VERSION:-4.2.0}
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 200m
    restart: always
    volumes:
      - pub_mongodb_conf:/data/configdb
      - pub_mongodb_data:/data/db
      - pub_mongodb_log:/var/log/mongodb
    container_name: standalone.pub-mongodb
    hostname: standalone.pub-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    networks:
      - custom-network
networks:
  custom-network:
    driver: bridge
volumes:
  pub_mongodb_data:
  pub_mongodb_log:
  pub_mongodb_conf: