services:
  pub_es8_01:
    image: elasticsearch:8.17.0
    container_name: pub_es8_01
    hostname: pub_es8_01
    restart: always
    ports:
      - 9200:9200
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - pub_es_data01:/usr/share/elasticsearch/data
      - pub_es_log1:/usr/share/elasticsearch/logs
      - ${PWD}/production_ready-elasticsearch-cluster.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "200m"
    networks:
      - custom-network
  pub_es8_02:
    image: elasticsearch:8.17.0
    container_name: pub_es8_02
    hostname: pub_es8_02
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - pub_es_data02:/usr/share/elasticsearch/data
      - pub_es_log2:/usr/share/elasticsearch/logs
      - ${PWD}/production_ready-elasticsearch-cluster.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "200m"
    networks:
      - custom-network
  pub_es8_03:
    image: elasticsearch:8.17.0
    container_name: pub_es8_03
    hostname: pub_es8_03
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - pub_es_data03:/usr/share/elasticsearch/data
      - pub_es_log3:/usr/share/elasticsearch/logs
      - ${PWD}/production_ready-elasticsearch-cluster.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "200m"
    networks:
      - custom-network
networks:
  custom-network:
    driver: bridge
volumes:
  pub_es_data01:
  pub_es_log1:
  pub_es_data02:
  pub_es_log2:
  pub_es_data03:
  pub_es_log3: