# ======================== Elasticsearch Configuration =========================
#
# NOTE: This configuration is for a production environment.
# Adjust according to your cluster size, hardware, and security requirements.

# ---------------------------------- Cluster -----------------------------------
cluster.name: pub-es-cluster  # Unique name for your cluster

# ----------------------------------- Node ------------------------------------
node.name: ${HOSTNAME}  # Uses the hostname as the node name
node.roles: [ data, ingest ]  # Define node roles (data, master, ingest, ml, etc.)

# ----------------------------------- Paths -----------------------------------
# path.data: /var/lib/elasticsearch  # Directory for storing index data
# path.logs: /var/log/elasticsearch  # Directory for logs

# ----------------------------------- Memory ----------------------------------
bootstrap.memory_lock: true  # Prevents Elasticsearch from swapping to disk
indices.memory.index_buffer_size: 10%

# ---------------------------------- Network ----------------------------------
network.host: 0.0.0.0  # Binds to the local network interface
http.port: 9200  # Port for HTTP API
transport.port: 9300  # Port for internal node communication

# --------------------------------- Discovery ---------------------------------
discovery.seed_hosts:  # List of master-eligible nodes for cluster formation
  - pub_es8_01
  - pub_es8_02
  - pub_es8_03
cluster.initial_master_nodes:  # Nodes that can elect a master
  - pub_es8_01
  - pub_es8_02
  - pub_es8_03

# ---------------------------------- Security ----------------------------------
xpack.security.enabled: false  # Enable security (requires license)
xpack.security.http.ssl.enabled: false
# xpack.security.http.ssl.keystore.path: certs/http-keystore.p12
# xpack.security.http.ssl.truststore.path: certs/http-truststore.p12
xpack.security.transport.ssl.enabled: false
# xpack.security.transport.ssl.verification_mode: certificate
# xpack.security.transport.ssl.keystore.path: certs/transport-keystore.p12
# xpack.security.transport.ssl.truststore.path: certs/transport-truststore.p12

# ---------------------------------- Monitoring -------------------------------
xpack.monitoring.collection.enabled: true  # Enable monitoring

# ---------------------------------- Indices ----------------------------------
action.destructive_requires_name: true  # Prevents wildcard deletion of indices
indices.query.bool.max_clause_count: 1024  # Increase if needed for complex queries

# ---------------------------------- Thread Pools -----------------------------
thread_pool.search.queue_size: 1000  # Adjust based on workload
thread_pool.write.queue_size: 500