version: '3.7'
services:
  redis:
    image: redis:${IMAGE_VERSION:-4.0}
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 200m
    restart: always
    volumes:
      - data:/data
      - conf:/etc/redis
      - log:/var/log/redis
    container_name: standalone.pub-redis
    hostname: standalone.pub-redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis_pass}
    ports:
      - 6379:6379
    networks:
      - custom-network
networks:
  custom-network:
    driver: bridge
volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: /opt/pub-redis/data/data
      o: bind
  conf:
    driver: local
    driver_opts:
      type: none
      device: /opt/pub-redis/data/conf
      o: bind
  log:
    driver: local
    driver_opts:
      type: none
      device: /opt/pub-redis/data/log
      o: bind
